# Generated by Django 4.2.7 on 2023-12-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclases', '0002_alumno_entregable_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
    ]
